madebygoogle/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/home', function () {
   return view('home');
});

Auth::routes();

Route::group(['middleware' => ['role:owner']], function () {
    Route::resource('/products', 'ProductsController');
    Route::get('products/{product}/delete', 'ProductsController@delete')->name('products.delete');
});

Route::group(['middleware' => ['role:owner|customer']], function () {
    Route::resource('/reviews', 'ReviewsController');
    Route::get('users/pdf', 'UsersController@PDF')->name('users/pdf');
});

Route::group(['middleware' => ['role:owner']], function () {
    Route::get('reviews/{review}/delete', 'ReviewsController@delete')->name('reviews.delete');
});

Route::group(['middleware' => ['role:owner']], function () {
    Route::resource('/categories', 'CategoriesController');
    Route::get('categories/{category}/delete', 'CategoriesController@delete')->name('categories.delete');
});

Route::group(['middleware' => ['role:owner']], function () {
    Route::resource('/users', 'UsersController');
    Route::get('users/{user}/edit', 'UsersController@edit')->name('users.edit');
    Route::get('users/{user}/delete', 'UsersController@delete')->name('users.delete');
});

madebygoogle/app/Http/Controllers/ReviewsController.php
<?php

namespace App\Http\Controllers;

use App\Product;
use App\Review;
use Illuminate\Support\Facades\Auth;
use Illuminate\Http\Request;

class ReviewsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $reviews = Review::all();
        return view('reviews.index', compact('reviews'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $products = Product::all();
        return view('reviews.create', compact('products'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $review = new Review();
        $review->title = $request->title;
        $review->user_id = Auth::user()->id;
        $review->product_id = $request->product_id;
        $review->body = $request->body;
        $review->rating = $request->rating;
        $review->save();

        return redirect('/reviews')->with('message', 'Review Added');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $review
     * @return \Illuminate\Http\Response
     */
    public function show(Review $review)
    {
        return view('reviews.show', compact('review'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param $review
     * @return \Illuminate\Http\Response
     */
    public function edit(Review $review)
    {
        $products = Product::all();
        return view('reviews.edit', compact('review'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param $review
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Review $review)
    {


        $review->title = $request->title;
        $review->user_id = Auth::user()->id;
        $review->product_id = $request->product_id;
        $review->body = $request->body;
        $review->rating = $request->rating;
        $review->save();

        return redirect('/reviews')->with('status', 'Review Edited');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param $review
     * @return \Illuminate\Http\Response
     */
    public function delete(Review $review)
    {
        return view('reviews.delete', compact('review'));
    }

    public function destroy(Review $review)
    {
        $review->delete();
        return redirect('/reviews')->with('status', 'Review Deleted');
    }
}

madebygoogle/resources/views/reviews/create.blade.php
@extends('layouts.layout')

@section('content')

    @if($errors->any())
        <div class="alert alert-danger">
            <ul>
                @foreach($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif

    @can('create reviews')
    <form method="post" action="/reviews">
        @csrf

        <div class="form-group">
            <label for="title">Title</label>
            <input type="text" name="title" id="title"class="form-control" placeholder="Title">
        </div>

        <div class="form-group">
            <label >Product List<label>
            <select class="form-control" name="product_id">
                @foreach ($products as $product)
                    <option value="{{$product->id}}">{{$product->productName}}</option>
                @endforeach
            </select>
        </div>

        <div class="form-group">
            <label for="body">Body</label>
            <input type="text" name="body" class="form-control" id="body"
                   aria-describedby="bodyHelp" placeholder="Body">
        </div>

        <div class="form-group">
            <label for="rating">Rating</label>
            <textarea class="form-control" name="rating" id="rating" rows="1" placeholder="Rating"></textarea>
        </div>

        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
 @else
    <div class="alert alert-danger">
        <p>You have no rights to make a review</p>
    </div>
    @endcan
@endsection

madebygoogle/resources/views/reviews/delete.blade.php
@extends('layouts.layout')

@section('content')
    <form method="post" action="/reviews/{{$review->id}}">
        @method('DELETE')
        @csrf
        <div class="form-group">
            <label for="title">Title</label>
            <input type="text" name="title" class="form-control" id="title"
                   aria-describedby="titleHelp" value="{{ $review->title }}" disabled>
        </div>

        <div class="form-group">
            <label for="username">Username</label>
            <input type="email" name="text" class="form-control" id="username"
                   aria-describedby="usernameHelp" value="{{ $review->username }}" disabled>
        </div>

        <div class="form-group">
            <label for="body">Body</label>
            <input type="email" name="text" class="form-control" id="body"
                   aria-describedby="bodyHelp" value="{{ $review->body }}" disabled>
        </div>

        <div class="form-group">
            <label for="body">Body</label>
            <input type="email" name="text" class="form-control" id="body"
                   aria-describedby="bodyHelp" value="{{ $review->body }}" disabled>
        </div>


        <div class="form-group">
            <label for="rating">Rating</label>
            <input type="text" name="rating" class="form-control" id="rating"
                   aria-describedby="ratingHelp" value="{{ $review->rating }}" disabled>
        </div>


        <button type="submit" class="btn btn-danger">Delete</button>
    </form>
@endsection

madebygoogle/resources/views/reviews/edit.blade.php
@extends('layouts.layout')

@section('content')
    <form method="post" action="{{ route('reviews.update', $review) }}">
        @method('PUT')
        @csrf
        <div class="form-group">
            <label for="title">Title</label>
            <input type="text" name="title" class="form-control" id="title"
                   aria-describedby="titleHelp" value="{{ $review->title }}">
        </div>

        <div class="form-group">
            <label for="body">Body</label>
            <input type="email" name="text" class="form-control" id="body"
                   aria-describedby="bodyHelp" value="{{ $review->body }}">
        </div>

        <div class="form-group">
            <label for="rating">Rating</label>
            <input type="text" name="rating" class="form-control" id="rating"
                   aria-describedby="ratingHelp" value="{{ $review->rating }}">
        </div>

        <button type="submit" class="btn btn-primary">Update</button>
    </form>
@endsection

madebygoogle/resources/views/reviews/index.blade.php
@extends('layouts.layout')

@section('content')
    <h1 class="mt-5">Reviews</h1>

    @if(session('message'))
        <div class="alert alert-success">
            {{ session('message') }}
        </div>
    @endif

    <nav class="nav">
        <ul class="nav nav-tabs">
            <li class="nav-item">
                <a class="nav-link active" href="{{ route('reviews.index') }}">Index</a>
            </li>
            <li>
            <li class="nav-item">
                @can('create reviews')
                <a class="nav-link" href="{{ route('reviews.create') }}">Create</a>
                @endcan
            </li>
        </ul>
    </nav>

    <table class="table">
        <thead class="thead-dark">
        <tr>
            <th scope="col">#</th>
            <th scope="col">Title</th>
            <th scope="col">Author</th>
            <th scope="col">Rating</th>
            <th scope="col">Actions</th>
        </tr>
        </thead>
        <tbody>
        @foreach($reviews as $review)
            <tr>
                <td>{{ $review->id }}</td>
                <td>{{ $review->title }}</td>
                <td>{{ $review->username }}</td>
                <td>{{ $review->rating }}</td>
                <td scope="row">
                    <a class="btn btn-primary" href="{{ route('reviews.show', ['review' => $review->id]) }}">Show</a>
                    @can('edit reviews')
                    &middot; <a class="btn btn-warning" href="{{ route('reviews.edit', ['review' => $review->id]) }}">Edit</a> &middot;
                    @endcan
                    @can('delete reviews')
                    <a class="btn btn-danger" href="{{ route('reviews.delete', ['review' => $review->id]) }}">Delete</a>
                    @endcan
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>
@endsection

madebygoogle/resources/views/reviews/show.blade.php
@extends('layouts.layout')

@section('content')
    <h1 class="mt-5">Reviews</h1>

    <nav class="nav">
        <ul class="nav nav-tabs">
            <li class="nav-item">
                <a class="nav-link" href="{{ route('reviews.index') }}">Index</a>
            </li>
            <li>
                <a class="nav-link" href="{{ route('reviews.create') }}">Create</a>
            </li>
            <li>
                <a class="nav-link active" href="{{  route('reviews.show', ['review' => $review->id]) }}">Review Details</a>
            </li>
        </ul>
    </nav>

    <div class="card">
        <div class="card-header">
            Review Details
        </div>
        <div class="card-body">
            <h2 class="card-title"> {{ $review->title }}</h2>

            <div class="form-group">
                <label for="username">Username</label>
                <input type="text"  name="username" class="form-control" id="username"
                       aria-describedby="usernameHelp" value="{{ Auth::user()->name }}" disabled>
            </div>

            <p class="cart"> {{ $review->body }}</p>
            <p class="card-text"> {{ $review->rating }}</p>
        </div>
    </div>

@endsection